name: "Test"

on:
  workflow_dispatch:
  #schedule:
  #  - cron: "18 18 * * 1,3,5"
  #push:
  #  branches: ["**"]
  #  paths:
  #    - "dist/**"
  #    - "src/**"
  #    - ".github/workflows/test.yaml"
  #    - "package*.json"
  #    - "requirements.txt"
  #    - "action.yml"

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      #- name: "Debug event.json"
      #  run: |
      #    cat "${GITHUB_EVENT_PATH}"

      - name: "Test Local Action"
        id: test
        uses: ./
        with:
          update: false
          summary: false
          #previous: "v1.0.2"

      - name: "Verify Outputs"
        env:
          JSON: ${{ steps.test.outputs.json }}
          MARKDOWN: ${{ steps.test.outputs.markdown }}
        run: |
          echo "json: '${{ env.JSON }}'"
          if [ -z '${{ env.JSON }}' ];then
            echo "No Output: json"
            exit 1
          fi
          echo "markdown: '${{ env.MARKDOWN }}'"
          if [ -z '${{ env.MARKDOWN }}' ];then
            echo "No Output: markdown"
            exit 1
          fi

      #- name: "Schedule Failure Notification"
      #  if: ${{ failure() && github.event_name == 'schedule' }}
      #  uses: sarisia/actions-status-discord@v1
      #  with:
      #    webhook: ${{ secrets.DISCORD_WEBHOOK }}
